---
layout: post
title: "Impressions of the Amazon Kindle"
date: 2008-10-22 00:02:12

uniqid: c8fea5c4-85c4-43fe-b82c-6bba8a5075a0
categories: 
 - Toys
---
<div class="wlWriterSmartContent" id="scid:0767317B-992E-4b12-91E0-4F059A8CECA8:ad189db6-1cf0-42d9-898a-7b534cc279ce" style="padding-right: 0px; display: inline; padding-left: 0px; padding-bottom: 0px; margin: 0px; padding-top: 0px">Technorati Tags: <a href="http://technorati.com/tags/Toys" rel="tag">Toys</a></div> <p>I treated myself to a Kindle a couple of months ago, and I'm pleased to say that I've been enjoying it a lot.&nbsp; I've read just over a half-dozen books on it so far; some at home and some while traveling.</p> <p>At first, the page turning buttons are a little frustrating because it is very easy to accidentally press them.&nbsp; This is something you train yourself not to do in pretty short order.</p> <p>The screen is very clear and easy to read, and has a configurable font size to cater for the eagle eyed through to the bleary eyed.&nbsp; There's no back light, so you need to provide your own illumination, just as you would for a regular dead-tree book.</p> <p>I've found it very easy to read.&nbsp; I'd read in some reviews that the visible page refresh takes a second or so when you turn a page, and that some people found that annoying.&nbsp; I view that as being equivalent to actually turning a page and giving your eyes a moment or so to move back up to the top left of the screen.&nbsp; I've started to press the "next page" button as I'm reading the last line; this is an unconscious action.</p> <p>The online store integration works well; you can literally pick out a book and have it appear on the device within a minute.&nbsp; I find this especially appealing if it's the weekend and I don't feel like taking an hour out to drive down to a book store, but it's also good if I finish a book while I'm on the road, particularly because I don't then have to lug an extra book or two back home at the end of the trip.</p> <p>The battery life is excellent if you remember to turn off the mobile antenna when you're not using it.&nbsp; I've been purchasing a book or two before a trip and been reading for several hours on the plane in each direction and an hour or so each night for several days on a single charge, and the battery is still only about half-way done when I arrive home.</p> <p>While I was in the UK, I was unable to use the wireless antenna to access the store, but I did download a couple of books to my laptop and copied them across via USB (you can mount the kindle as a mass storage device).</p> <p>My only real annoyance with the device is the page turning buttons; they're quite easy to nudge as you're settling down to read, so you have to click the button for the opposite direction to correct that.</p> <p>So, in all, I'm really enjoying the device; a little pricey, perhaps, but it's the kind of thing I've been waiting for for several years--definitely way ahead of reading ebooks almost half a decade ago on my old HP iPAQ.</p>