#!/usr/bin/php
<?php # vim:ts=2:sw=2:et:ft=php:
# Reads posts and builds out the index data
include 'inc/rest.php';
include 'inc/projects.php';

if (php_sapi_name() != 'cli') {
  header("Location: $WEBROOT");
  exit;
}

wfo_get_project_data();

