#!/usr/bin/php
<?php # vim:ts=2:sw=2:et:ft=php:

# 1st param is the title
# remaining params are tags

include_once dirname(__FILE__) . '/common.php';
include_once dirname(__FILE__) . '/rest.php';

$title = $argv[1];
array_shift($argv); # script name
array_shift($argv); # title
$tags = $argv; # tags
$slug = prettify($title);

if (!strlen($title) || !strlen($slug)) {
  echo "Usage: ./inc/newpost 'title' tag1 tag2\n";
  exit(1);
}

$date = time();

$meta = new stdclass;
$meta->type = 'blog';
$meta->subject = "$title";
$meta->uniqid = strtolower(trim(shell_exec('uuidgen')));
$meta->date = strftime('%Y-%m-%d %H:%M', $date);
$meta->tags = $tags;
$path = "posts/" . strtolower(date('Y/M', $date)) . "/$slug";

if (!is_dir($path)) {
  system("mkdir -p '$path'");
}

if (!file_exists("$path/meta.json")) {
  wfo_file_put("$path/meta.json", json_encode($meta));
}
if (!file_exists("$path/index.html")) {
  wfo_file_put("$path/index.html", "<p>\n</p>");
}

echo "$title: $slug\n";
echo "Edit the post at:\n";
echo "$path/meta.json\n$path/index.html\n";
